<?xml version="1.0" encoding="utf-8"?><Database Name="BisManiaTicketing" Class="BMTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FORGOTTEN-ADMIN;Initial Catalog=BisManiaTicketing;Integrated Security=True" SettingsObjectName="Bis_Mania_Ticketing.Properties.Settings" SettingsPropertyName="BisManiaTicketingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Otobus" Member="Otobus">
    <Type Name="Otobus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OtobusName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Otobus_Bus" Member="Bus" ThisKey="Id" OtherKey="IdOtobus" Type="Bus" />
      <Association Name="Otobus_OtobusTicketTypeRoute" Member="OtobusTicketTypeRoutes" ThisKey="Id" OtherKey="IdOtobus" Type="OtobusTicketTypeRoute" />
    </Type>
  </Table>
  <Table Name="dbo.TicketType" Member="TicketTypes">
    <Type Name="TicketType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TicketType_Bus" Member="Bus" ThisKey="Id" OtherKey="IdTicketType" Type="Bus" />
      <Association Name="TicketType_Ticket" Member="Tickets" ThisKey="Id" OtherKey="IdTicketType" Type="Ticket" />
      <Association Name="TicketType_OtobusTicketTypeRoute" Member="OtobusTicketTypeRoutes" ThisKey="Id" OtherKey="IdTicketType" Type="OtobusTicketTypeRoute" />
    </Type>
  </Table>
  <Table Name="dbo.Venue" Member="Venues">
    <Type Name="Venue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VenueName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VenueLocation" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Venue_Route" Member="Routes" ThisKey="Id" OtherKey="RouteDeparture" Type="Route" />
      <Association Name="Venue_Route1" Member="Routes1" ThisKey="Id" OtherKey="RouteDestination" Type="Route" />
    </Type>
  </Table>
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RouteDeparture" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RouteDestination" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Route_OtobusTicketTypeRoute" Member="OtobusTicketTypeRoutes" ThisKey="Id" OtherKey="IdRoute" Type="OtobusTicketTypeRoute" />
      <Association Name="Route_Schedule" Member="Schedules" ThisKey="Id" OtherKey="IdRoute" Type="Schedule" />
      <Association Name="Venue_Route" Member="Venue" ThisKey="RouteDeparture" OtherKey="Id" Type="Venue" IsForeignKey="true" />
      <Association Name="Venue_Route1" Member="Venue1" ThisKey="RouteDestination" OtherKey="Id" Type="Venue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bus" Member="Bus">
    <Type Name="Bus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdOtobus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTicketType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BusNumber" Type="System.String" DbType="VarChar(11)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BusModel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalSeat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Bus_Schedule" Member="Schedules" ThisKey="Id" OtherKey="IdBus" Type="Schedule" />
      <Association Name="Otobus_Bus" Member="Otobus" ThisKey="IdOtobus" OtherKey="Id" Type="Otobus" IsForeignKey="true" />
      <Association Name="TicketType_Bus" Member="TicketType" ThisKey="IdTicketType" OtherKey="Id" Type="TicketType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentMaster" Member="PaymentMasters">
    <Type Name="PaymentMaster">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.String" DbType="VarChar(15)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdBooking" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPassenger" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PaymentMaster_PaymentDetail" Member="PaymentDetails" ThisKey="Id" OtherKey="IdPaymentMaster" Type="PaymentDetail" />
      <Association Name="Booking_PaymentMaster" Member="Booking" ThisKey="IdBooking" OtherKey="Id" Type="Booking" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentDetail" Member="PaymentDetails">
    <Type Name="PaymentDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPaymentMaster" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTicket" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="PaymentMaster_PaymentDetail" Member="PaymentMaster" ThisKey="IdPaymentMaster" OtherKey="Id" Type="PaymentMaster" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seats" Member="Seats">
    <Type Name="Seat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdSchedule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeatsNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Available" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Seat_Ticket" Member="Tickets" ThisKey="Id" OtherKey="IdSeat" Type="Ticket" />
      <Association Name="Schedule_Seat" Member="Schedule" ThisKey="IdSchedule" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBooking" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPassenger" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSeat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTicketType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Seat_Ticket" Member="Seat" ThisKey="IdSeat" OtherKey="Id" Type="Seat" IsForeignKey="true" />
      <Association Name="TicketType_Ticket" Member="TicketType" ThisKey="IdTicketType" OtherKey="Id" Type="TicketType" IsForeignKey="true" />
      <Association Name="Booking_Ticket" Member="Booking" ThisKey="IdBooking" OtherKey="Id" Type="Booking" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OtobusTicketTypeRoute" Member="OtobusTicketTypeRoutes">
    <Type Name="OtobusTicketTypeRoute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdOtobus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTicketType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdRoute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(22,0) NOT NULL" CanBeNull="false" />
      <Association Name="Otobus_OtobusTicketTypeRoute" Member="Otobus" ThisKey="IdOtobus" OtherKey="Id" Type="Otobus" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Route_OtobusTicketTypeRoute" Member="Route" ThisKey="IdRoute" OtherKey="Id" Type="Route" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="TicketType_OtobusTicketTypeRoute" Member="TicketType" ThisKey="IdTicketType" OtherKey="Id" Type="TicketType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdRoute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FinalPrice" Type="System.Decimal" DbType="Decimal(22,0) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Schedule_Seat" Member="Seats" ThisKey="Id" OtherKey="IdSchedule" Type="Seat" />
      <Association Name="Schedule_Booking" Member="Bookings" ThisKey="Id" OtherKey="IdSchedule" Type="Booking" />
      <Association Name="Bus_Schedule" Member="Bus" ThisKey="IdBus" OtherKey="Id" Type="Bus" IsForeignKey="true" />
      <Association Name="Route_Schedule" Member="Route" ThisKey="IdRoute" OtherKey="Id" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Booking" Member="Bookings">
    <Type Name="Booking">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdSchedule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPassenger" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Paid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Booking_PaymentMaster" Member="PaymentMasters" ThisKey="Id" OtherKey="IdBooking" Type="PaymentMaster" />
      <Association Name="Booking_Ticket" Member="Tickets" ThisKey="Id" OtherKey="IdBooking" Type="Ticket" />
      <Association Name="Schedule_Booking" Member="Schedule" ThisKey="IdSchedule" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="Passenger_Booking" Member="Passenger" ThisKey="IdPassenger" OtherKey="Id" Type="Passenger" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GenderList" Member="GenderLists">
    <Type Name="GenderList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenderName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GenderList_Passenger" Member="Passengers" ThisKey="Id" OtherKey="IdGender" Type="Passenger" />
    </Type>
  </Table>
  <Table Name="dbo.Passenger" Member="Passengers">
    <Type Name="Passenger">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NIK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdGender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Passenger_Booking" Member="Bookings" ThisKey="Id" OtherKey="IdPassenger" Type="Booking" />
      <Association Name="GenderList_Passenger" Member="GenderList" ThisKey="IdGender" OtherKey="Id" Type="GenderList" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteBus" Method="DeleteBus">
    <Parameter Name="IdBus" Parameter="idBus" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>